### ISSUE TITLE
Update to ES6 and the Feathers 2.0

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-mongodb#16]

**Comment by joshuajabbour** [comment]
I'd definitely prefer to use the core mongo library over an ORM, so would love to see this updated. Can you detail what needs to be done (I can't really find an 2.0 docs anywhere)? I'd happily take a crack at it if I knew what I needed to focus on...

**Comment by daffl** [comment]
The 2.0 docs are being worked on at http://docs.feathersjs.com (there will also be a guide on how to create a plugin). Plugins with the new infrastructure can be initialized with the [plugin generator](https://github.com/feathersjs/generator-feathers-plugin) (`yo feathers-plugin`). I'll follow up in #20 with the specific steps.

**Comment by daffl** [comment]
Also, all old adapters (including the current version of this one) and custom services will still work with Feathers 2.0. There has been no breaking changes there.

**Comment by joshuajabbour** [comment]
:+1: Sounds good. I'll give it a go...

**Comment by ekryski** [comment]
I could push up what I've got locally. I sort of forget where it is at but it might be helpful.

**Comment by joshuajabbour** [comment]
@ekryski That'd be great.

**Comment by joshuajabbour** [comment]
@ekryski Any chance you could push your local work to a branch here so I can start there? I'm just now getting started tackling this, and don't want to duplicate work...

**Comment by ekryski** [comment]
@joshuajabbour sorry for the delay. I hope that you haven't done a ton of work on it so far :grin. When I finally had time to look at what I had done I realized that it was almost complete. It's just the tests that are being stupid.

I've pushed up a PR (#24) that should take care of everything and get this repo up to date with Feathers 2. Once we get the tests passing we'll issue a new 2.0 release.

**Comment by ekryski** [comment]
Closed by #24

**Comment by ekryski** [comment]
Alrighty apologies again for the delay and any inconvenience @joshuajabbour and anyone else that was waiting on this. I've released 2.1 which brings this repo up to date.
