### ISSUE TITLE
Migrate to feathers-errors >= 1.1.x

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-mongodb#17]

**Comment by ichiriac** [comment]
Hi, i've installed a fresh npm install with mongodb and i get this error :

```
.../node_modules/mongodb/lib/mongodb/connection/base.js:246
        throw message;
        ^
TypeError: Cannot read property 'NotFound' of undefined
```

I suppose it's related ?

**Comment by daffl** [comment]
What Feathers version did you install? It shouldn't happen with v1.x but we should indeed have this repository reference errors directly. I can probably do that later today in a patch release.

**Comment by daffl** [comment]
I made a new release (1.1.1) that should fix the issue as well.
