### ISSUE TITLE
Upgrade to mongo-native 2.1

### ISSUE THREAD

**Issue by joshuajabbour** [feathersjs/feathers-mongodb#20]
This might also eliminate the need for Mongoskin, though it depends on what you're using it for (mongo-native 2 supports promises).

**Comment by daffl** [comment]
Changing to the mongo-native adapter and away from Mongoskin would be a great first step. If you have experience with mongo-native it would be a huge help if you could give migrating the repository as it is right now a try and then we can iterate from there (the rest actually shouldn't be that much to change).

**Comment by joshuajabbour** [comment]
Any idea why Mongoskin was used in the first place? I don't see anything obvious, but could be overlooking something.

And yeah, I've written adapters for mongo-native 2 before, so I understand it fairly well. I will give this a pass soon.

**Comment by daffl** [comment]
Back when the adapter was started (~ 2 years ago) that seemed like the most easy to use choice. That's the only reason.

**Comment by joshuajabbour** [comment]
And it probably was back then. :wink: Mongo-native >=2 is much improved...

**Comment by joshuajabbour** [comment]
I'm just going to start tracking some notes in here as I explore:

- Removing Mongoskin will definitely make this a major API change and therefore a major version bump. Since it seems like the fact that Mongoskin was even used was somewhat hidden from end users, hopefully it won't be a problem and I'd be okay with it. But upgrading would require rework for any users that relied on the extensions Mongoskin added to the Mongo API (which aren't really needed any more IMO). As mentioned, continuing to use v1 would still be an option...

- [ ] TODO: Fix `_id` option (this [currently doesn't work](https://github.com/feathersjs/feathers-mongodb/issues/22) afaik)

**Comment by daffl** [comment]
Yes. It would definitely be a 2.0 which I think is totally ok. Another breaking change that we made in all the other adapters is that they don't directly depend on the database connector itself.

Basically a users establishes the connection themselves and then just passes a reference to the database/collection/model to the adapter (e.g. [feathers-sequelize](https://github.com/feathersjs/feathers-sequelize) just takes a Sequelize model but does not depend on Sequelize itself). That way we could get rid of all the special initialization cases like it is currently done in https://github.com/feathersjs/feathers-mongodb/blob/master/lib/index.js#L31.

**Comment by ekryski** [comment]
Ya we will be removing mongoskin. There isn't any need for it. It's just that setting up the connection in mongodb is dumb and will follow the same pattern as [feathers-waterline](https://github.com/feathersjs/feathers-waterline/blob/master/example/app.js#L50)

**Comment by joshuajabbour** [comment]
@ekryski Sounds like you're going to take an initial pass at upgrading the adapter. I'll hold off until you're done then...

**Comment by daffl** [comment]
@joshuajabbour Did you already start? We're trying to wrap up the Feathers 2 release this week so there are a bunch of other things that we can take care of first. I'd hate for you to throw away some of your work.

**Comment by ekryski** [comment]
@joshuajabbour ya feel free to take a crack. I'll look right now to see where I had left off and then push it up like I said I would a week ago :disappointed:

**Comment by ekryski** [comment]
Closed by #24
