### ISSUE TITLE
how to insert?

### ISSUE THREAD

**Issue by vectorselector** [feathersjs/feathers-mongodb#23]
I don't see any documentation on how to actually use the db connection for inserting (not querying)

maybe i'm just being a noob but I think the docs should define how one is to use this db connection...

**Comment by vectorselector** [comment]
ok, so aside from rest, i want to explicitly insert and i found out by guessing that there is a method called "create" papering over mongos "insert"
again, i'm a noob and probably being dumb: but why are we changing mongo verbs to fit a concept called crud?
i know the general basics of rest, but I don't understand how our http req/res and url correspond implicitly to crud... IMO these are unstated assumptions that should be made explicit.

in my case, i am uploading an image file via the multer package, and i want the metadata (path filename etc) to be inserted into a mongo collection at the same time as the upload (versus chunked upload directly into mongo...) so I simply added the line:

mongodb({db:'feathers', collection:'masterCards'}).create(req.file);

and it's working...
but this would be good to speak about, IMO

**Comment by marshallswain** [comment]
`feathers-mongodb` is a database adapter for Feathers, which implements maintaining fully RESTful APIs as one of its primary principles.  There are a couple of people currently updating this adapter to bring it up to par with the other adapters.  In the meantime, I would recommend using the `feathers-mongoose` adapter and turning off Mongoose schemas (which is as simple as providing an empty object as your schema, I believe.) until `feathers-mongodb` is updated to the new API.  Turning off Mongoose schemas should make it work pretty similar to this adapter.

Also, check out the Feathers docs here: http://docs.feathersjs.com.

You can find the service methods here: http://docs.feathersjs.com/services/readme.html#service-methods

**Comment by daffl** [comment]
We are working on the v2 docs at http://docs.feathersjs.com/ but how those methods correspond to REST and websocket calls should also be documented fairly detailed in the current documentation at http://feathersjs.com/docs/#toc10 and in the [quick start guide](http://feathersjs.com/quick-start).

**Comment by vectorselector** [comment]
thanks for the info, folks

**Comment by marshallswain** [comment]
http://feathersjs.com might be a better introduction to see how it works and compares to Meteor, Sails, etc.
