### ISSUE TITLE
Support $search

### ISSUE THREAD

**Issue by ekryski** [feathersjs/feathers-mongodb#33]
This is a proposed special attribute that allows you to fuzzy match a property. Possibly even multiple properties and/or nested documents.

Suggested syntax:

```js
name: {
  $search: ['alice', 'Alice', 'bo', /$bob/i]
}
```

Following similar syntax to our other special query filters, this would allow you to filter by a singular value, multiple values (treated like an **or**) and/or regular expressions directly.

Internally mongodb requires a $regex query but we can fairly easily build a singular regex from this array. Another internal construct that mongodb provides is [`$text`](https://docs.mongodb.org/manual/reference/operator/query/text/) so we might be able to use that for full text search.

**Comment by daffl** [comment]
See https://github.com/feathersjs/feathers/issues/334
