### ISSUE TITLE
objectifyId only converting for _id field

### ISSUE THREAD

**Issue by joshuajabbour** [feathersjs/feathers-mongodb#40]
Is there a reason why [`objectifyId()` only converts an id if the id field is `_id`](https://github.com/feathersjs/feathers-mongodb/blob/c8769695ceebb1fc7848cb5b519943d2b6f30544/src/utils.js#L26)? This currently makes it impossible to use an ObjectID in another field as the primary key.

**Comment by daffl** [comment]
Can't the other fields be converted in a `before` hook?

```js
app.service('myservice').before({
  find(hook) {
    hook.params.query.otherField = new ObjectId(hook.params.query.otherField);
  }
});
```

**Comment by joshuajabbour** [comment]
Possibly, I haven't tried that. I'd also prefer to not have to depend on hooks being enabled. (I'm writing a service that extends the default Mongo one, and I'd like it to just work.)

A better workaround IMO would be moving the utility functions into the service, so they could be overridden. That would make them cleaner overall, and would solve other problems as well.

Would that be considered? If so, I'll put together a PR...

**Comment by daffl** [comment]
Absolutely. Probably similar to your PR from #36. Then I can release both those PRs together.
