### ISSUE TITLE
Unique index on idField?

### ISSUE THREAD

**Issue by joshuajabbour** [feathersjs/feathers-mongodb#46]
Should this adapter create a unique index on the `idField` (if it's not `_id`)? Or should that be up to the user to do manually out-of-band? Right now, if you set the idField to something else (like `id`), you can create multiple/duplicate documents with that id.

**Comment by marshallswain** [comment]
I don't think the adapter should create indexes or unique rules, but it would be nice of us to mention how to do it in the docs.

**Comment by daffl** [comment]
I was just replying and then @marshallswain beat me to it.

We changed the adapters from doing all the connection and collection setup stuff themselves to just passing the initialized collection. I agree that it makes sense to have the user do it but we should mention it in the docs. Is there maybe also a way to check if there is a unique index on the passed id field and throw a warning?

**Comment by joshuajabbour** [comment]
Yes, we can check for the index, and I do think we should throw if there isn't one. Adding the index should be required, otherwise it's not actually an id field.

**Comment by joshuajabbour** [comment]
So this becomes really difficult due to the tricky that's demonstrated in the tests. Specifically, initializing a service without a `Model` and later adding it with `app.service('people').Model = db.collection('people')`. If this is a common pattern, there's no way to validate the proper index.

I think I'll create a method on the service that can validate it, and then in the constructor validate that `Model` is a Mongo collection and if so, run the index check. If not, it can't run. Not as safe as I'd like, but I guess if users are initializing services without a db, then there's not much to be done.

**Comment by daffl** [comment]
It's really just a workaround for the asynchronous initialization of the plugin (which you correctly pointed out we should solve properly). Could we add a `verifyIndices` method that can be called manually but also runs in the constructor (if `this.Model` is set)?

**Comment by joshuajabbour** [comment]
Yeah, that's basically the route I've taken. If `Model` exists, then we check it for the proper index. If not, it's up to the user. I'll update the docs to clarify how this works, and that the index is required for the id field to work properly.

**Comment by daffl** [comment]
I just merged #62 which doesn't have the weird workaround for setting the model. Are we still going to add the index check?
