### ISSUE TITLE
TypeError: errors.handler is not a function

### ISSUE THREAD

**Issue by kulakowka** [feathersjs/feathers-mongodb#57]
I tried to run the sample and received an error:

```
TypeError: errors.handler is not a function
```
It is obvious that the error here is this line:
https://github.com/feathersjs/feathers-mongodb/blob/master/example/app.js#L33-L34

I think an example is outdated?

**Comment by kulakowka** [comment]
It seems that the example in README.md file is outdated.

I corrected it. https://github.com/feathersjs/feathers-mongodb/pull/58

**Comment by daffl** [comment]
Closed via https://github.com/feathersjs/feathers-mongodb/pull/60, thank you!
