### ISSUE TITLE
How to unset a property of document

### ISSUE THREAD

**Issue by StanleyAM** [feathersjs/feathers-mongodb#72]
Hi, this plugin doesn't support $unset at mongodb so how to unset a property of document?

Currently work around:
1. gets the complete object of document
2. delete the property of object
3. use UPDATE method to that document

Is there any better proper way?

Thanks.

**Comment by daffl** [comment]
`service.update(id, { $unset: { myfield: '' } })` should work.

**Comment by StanleyAM** [comment]
Hi @daffl ,

Thanks to your reply. Yes, your suggestion works perfectly.

But now I hava a situation: I want to setting my user's password and delete one user's field

`service.update(id, { $set: { pw: "12345678" } $unset: { myfield: '' } })`

and I use `hooks.hashPassword({ passwordField: "pw" }),`

It will not hash the 'pw' field.

Thanks.

**Comment by daffl** [comment]
The best thing for this is probably to use

```js
service.patch(id, { pw: "12345678", myfield: null });
```

Or create your own `hashPassword` hook that runs the hash also for `data.$set.pw` (currently it only runs for `data.pw`).

Going to close this issue but feel free reopen or create another if you have other questions.
