### ISSUE TITLE
No Open Connections

### ISSUE THREAD

**Issue by abnovak** [feathersjs/feathers-mongodb#8]
I'm getting a no open connections error fairly frequently while developing our app. I see on line 25 of your MongoService module that you specifically call out that you're creating a new connection for each service. Are you providing a mechanism to control the number of connections, or whether or not it can reuse an open connection rather than create a new one?

**Comment by ekryski** [comment]
In the mongoose lib we just have the option for reconnect default to true.

**Comment by ekryski** [comment]
Revisiting this, I guess autoreconnect should be added as a default then. I'll make sure it also gets into PR #11.
