### ISSUE TITLE
the latest npm package is not updated?

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers-mongodb#89]
### Steps to reproduce

I might be wrong, but it's so weird that the npm package v2.8.0 is not the same with the latest repo on github. After `npm i -S feathers-mongodb`, the `\lib\index.js#279` is:

```js
return Promise.reject('Not replacing multiple records. Did you mean `patch`?');
```
but the same line in the repo forked from github's master branch (after compliation with `npm test`) is:

```js
return Promise.reject(new _feathersErrors2.default.BadRequest('Not replacing multiple records. Did you mean `patch`?'));
```
The later one is OK, but the first one generates wrong format of error.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### System configuration

Tell us about the applicable parts of your setup.

**Module versions** (especially the part that's not working):
2.8.0
**NodeJS version**:
7.10.0
**Operating System**:
windows 10 with linux sub system
**Browser Version**:

**React Native Version**:

**Module Loader**:

**Comment by daffl** [comment]
Closed via v2.8.0
