### ISSUE TITLE
Can't set properties on custom adapter extended from feathers-mongodb

### ISSUE THREAD

**Issue by indigokidsgames** [feathersjs/feathers-mongodb#93]
### Steps to reproduce

- https://gist.github.com/indigokidsgames/e11ab7626837c0ecba79648202229fe8

### Expected behavior
The `this.app` property that is being set at `setup()` is present in other instance methods.

### Actual behavior
`this.app` is undefined when accessed from another method.

### System configuration

**Module versions**: feathers-mongodb@2.9.0, feathers@2.1.7

**NodeJS version**: v8.4.0

**Operating System**: OSX 10.11.6

**Comment by daffl** [comment]
How are you calling `testFn`?

Internally Feathers [creates a copy of a service object](https://docs.feathersjs.com/api/application.html#servicepath) so you can't necessarily rely on the prototype chain you'd expect (especially for [legacy properties like __proto__](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Object/proto)). It should have all the properties and methods of the original service object however so there might be an issue there.

**Comment by indigokidsgames** [comment]
In real life `testFn` would be called from the code. I'm trying to
